spring:
  datasource:
    url: jdbc:h2:mem:hogwarts_db
    username: sa
    password: sa
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  flyway:
    locations: classpath:db/migration/h2

api:
  endpoint:
    base-url: /api/v1

server:
  port: 80