spring:
  datasource:
    url: jdbc:h2:mem:hogwarts_db
    username: sa
    password: sa
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

api:
  endpoint:
    base-url: /api/v1

ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
    api-key: ${AI_OPENAI_API_KEY:YOUR_API_KEY}

server:
  port: 8080